name: Keep-Alive Workflow
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: curl -s https://coeteco-hack-2-b.onrender.com/ > /dev/null
